AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  project-dudu

  Sample SAM Template for project-dudu

Globals:
  Function:
    Timeout: 120
    MemorySize: 256

Resources:

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: arn:aws:logs:*:*:*

  GetAllMissionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/missions/get_all_missions/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetAllMissions:
          Type: Api
          Properties:
            RestApiId: !Ref MissionApi
            Path: /get_all_missions
            Method: get

  GetOneMissionFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: modules/missions/get_one_mission/
      Handler: app.lambda_handler
      Runtime: python3.12
      Role: !GetAtt LambdaExecutionRole.Arn
      Architectures:
        - x86_64
      Events:
        GetAllMissions:
          Type: Api
          Properties:
            RestApiId: !Ref MissionApi
            Path: /get_one_mission
            Method: get

  MissionApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MissionApi
      StageName: Prod

Outputs:
  LambdaExecutionRoleArn:
    Description: "Implicit IAM Role created for Lambda function"
    Value: !GetAtt LambdaExecutionRole.Arn
  GetAllMissionsApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Get All Missions function"
    Value: !Sub "https://${MissionApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_all_missions/"
  GetOneMissionApiUrl:
    Description: "API Gateway endpoint URL for Prod stage for Get One Mission function"
    Value: !Sub "https://${MissionApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/get_one_mission/"
  GetAllMissionsFunctionArn:
    Description: "Get All Missions Lambda Function ARN"
    Value: !GetAtt GetAllMissionsFunction.Arn
  GetOneMissionFunctionArn:
    Description: "Get One Mission Lambda Function ARN"
    Value: !GetAtt GetOneMissionFunction.Arn